# Generated by Django 4.1.1 on 2023-02-03 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbaseinfo',
            name='id',
        ),
        migrations.AddField(
            model_name='userbaseinfo',
            name='userID',
            field=models.BigIntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='userSecurityInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_addr', models.EmailField(max_length=128)),
                ('phone_num', models.CharField(max_length=64)),
                ('userInfo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userauth.userbaseinfo')),
            ],
        ),
        migrations.CreateModel(
            name='userAuthenticInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_encrypt_key', models.CharField(max_length=128)),
                ('token_passkey', models.CharField(max_length=128)),
                ('userInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.userbaseinfo')),
            ],
        ),
    ]
