# Generated by Django 4.1.1 on 2023-02-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_remove_userbaseinfo_id_userbaseinfo_userid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersecurityinfo',
            name='userInfo',
        ),
        migrations.RemoveField(
            model_name='userbaseinfo',
            name='userID',
        ),
        migrations.AddField(
            model_name='userbaseinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='userAuthenticInfo',
        ),
        migrations.DeleteModel(
            name='userSecurityInfo',
        ),
    ]
