# Generated by Django 4.1.1 on 2023-02-04 09:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_remove_usersecurityinfo_userinfo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='serverUniversalKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_generate', models.DateTimeField(auto_now_add=True)),
                ('key_name', models.CharField(max_length=60)),
                ('key_type', models.CharField(max_length=60)),
                ('key_description', models.CharField(max_length=200)),
                ('key_value', models.CharField(max_length=2048)),
            ],
        ),
        migrations.AlterField(
            model_name='userbaseinfo',
            name='password',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='userbaseinfo',
            name='username',
            field=models.CharField(max_length=64),
        ),
        migrations.CreateModel(
            name='userTokenInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('time_generate', models.DateTimeField(auto_now_add=True)),
                ('time_lastuse', models.DateTimeField()),
                ('tokenKey', models.CharField(max_length=16)),
                ('encryptInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.serveruniversalkey')),
                ('userInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.userbaseinfo')),
            ],
        ),
        migrations.CreateModel(
            name='userSecurityInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=64)),
                ('phone_number', models.CharField(max_length=40)),
                ('token_expire_duration', models.DurationField(default=datetime.timedelta(days=180))),
                ('userInfo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userauth.userbaseinfo')),
            ],
        ),
    ]
